my_fav_numbers = set([0, 1, 2, 3, 4])
my_fav_numbers.add(5)
my_fav_numbers.add(6)
print(my_fav_numbers)
my_fav_numbers.remove(6)
print(my_fav_numbers)
friend_fav_numbers = set([20, 21, 22, 23, 24,])
our_fav_numbers = my_fav_numbers.union(friend_fav_numbers)
print(our_fav_numbers)